image:
  file: .gitpod.Dockerfile

tasks:
 - init: |
    cd src
    export JTR=../run/john
    export ASAN_OPTIONS=symbolize=1
    export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer)
    ./configure --enable-werror
    make -sj4
